---
title: "leafing_flowering_lag"
output: html_document
date: "2023-05-18"
---

-------------------
# the whole story
get data
```{r message=FALSE, warning=FALSE}
source("scripts/function_npn_select_model_data.R")
npndata <- get_modelled_data()
```

# Introduction
flower time and amount is important phenology related to seed production and pollen.

studying them need data

lots of trees are wind pollinated trees which has catkin flowers, and is hard to observe

while leafing observation is easier by satillite images

so we want to using leaf to infer flower, at least inform the potential species that can be infer from leaf to flower

# leaf flower correlation
whether leaf and flower is correlated (select highly related species)
```{r message=FALSE, warning=FALSE}
source("scripts/plot_cc_stat_1speciespergenus.R")
print(combined_plot)
rm(list = setdiff(ls(), "npndata"))

```

# leaf flowering calendar day lag and gdd lag (average + std)
select species with small std
```{r message=FALSE, warning=FALSE}
source("scripts/table_lag_statistics.R")
source("scripts/plot_lag_statistics.R")
print(combinefigure)
rm(list = setdiff(ls(), "npndata"))
```


# compare calendar day and gdd which is better (use flower instead of lag to compare?) | using leaf or climate directly
use lag
```{r message=FALSE, warning=FALSE}
source("scripts/table_lag_statistics.R")
source("scripts/plot_lag_statistics_compare.R")
print(gdd_doy)
print(leaf_climate)
rm(list = setdiff(ls(), "npndata"))
```

# lag~climate relationship
```{r message=FALSE, warning=FALSE}
source("scripts/plot_lag_climate.R")
print(combined_plot_day)
print(combined_plot_gdd)
rm(list = setdiff(ls(), "npndata"))

```

---------
# SI

## data availability: need to be combined in a figure, no need to separate for genus
```{r include=FALSE}
source("scripts/plot_avail_individual_yr.R")

```

## lag histogram: the distribution behind the mean and std we repoted
This is important information, maybe think about making a large figure
```{r include=FALSE}
source("scripts/plot_histogram_of_lag.R")

```




