---
title: 'play NAB data'
embed-resources: true
author: "Yi Liu"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
format:
  html:
    code-folding: show
    highlight: textmate
    number-sections: true
    theme: flatly
    toc: TRUE
    toc-depth: 4
    toc-float:
      collapsed: false
      smooth-scroll: true
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(patchwork)
library(ggtext)
library(readr)

library(batchplanet)

```

# get NAB data

```{r}
nab <- read_rds("/Volumes/seas-zhukai/datasets/vegetation/NAB/clean/2023-04-25/nab_renew.rds")

# Fordham College at Lincoln Center
NY_pollen <- nab %>% 
  filter(stationid == "5effe609-c645-4620-bc99-a3b34934897c")

NY_maple <- NY_pollen %>% 
  filter(taxa == "Quercus") %>% 
  select(date, count) %>% 
  complete(date = seq(min(date), max(date), by = "day"))
```

```{r}
NY_maple_ts <- NY_maple %>%
  arrange(date) %>%
  tibble::column_to_rownames("date")

```


```{r}
count_vector <- NY_maple$count
smoothed_counts <- whittaker_smoothing_filling(
  x = count_vector,  # Only the numeric count values
  lambda = 100,
  maxgap = 60,
  minseg = 30
)

```


```{r}
smoothed_data <- data.frame(
  date = NY_maple$date,
  original = count_vector,
  smoothed = smoothed_counts
)
```

```{r}
ggplot(smoothed_data) +
  geom_point(aes(x = date, y = original, color = "original")) +
  geom_line(aes(x = date, y = smoothed, color = "smoothed"), linewidth = 2, alpha = 0.75) +
  scale_color_manual(values = c("original" = "black", "smoothed" = "dark green")) +
    scale_y_log10() +  # <-- This sets the y-axis to log scale
  theme_minimal() +
  labs(
    x = "Date",
    y = "Value",
    color = ""
  ) +
  theme(legend.position = "bottom")
```


```{r}
# First, add a year column to the data
smoothed_data <- smoothed_data %>%
  mutate(year = lubridate::year(date))

# Then create the plot with facets by year
ggplot(smoothed_data) +
  geom_point(aes(x = date, y = original, color = "original")) +
  geom_line(aes(x = date, y = smoothed, color = "smoothed"), linewidth = 2, alpha = 0.75) +
  scale_color_manual(values = c("original" = "black", "smoothed" = "dark green")) +
  scale_y_log10() +  # <-- This sets the y-axis to log scale
  theme_minimal() +
    facet_wrap(~year, scales = "free_x") +
  labs(
    x = "Date",
    y = "Log(Value)",
    color = ""
  ) +
  theme(legend.position = "bottom")


```


