---
title: 'play herbarium data'
embed-resources: true
author: "Yi Liu"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
format:
  html:
    code-folding: show
    highlight: textmate
    number-sections: true
    theme: flatly
    toc: TRUE
    toc-depth: 4
    toc-float:
      collapsed: false
      smooth-scroll: true
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(patchwork)
library(ggtext)

```

# get herbarium data

```{r eval=FALSE}
raw <- read.csv("../data/Herbarim_flower/combined_occ_img_downloaded.csv") %>% 
  dplyr::select(day, month, year, startDayOfYear, coordinateUncertaintyInMeters, decimalLongitude, decimalLatitude, filename_image, species, genus,family)

phenology <- read.csv("../data/Herbarim_flower/phenology.csv") %>% 
  mutate(filename_image = gsub(".txt", "", file_name))

joint_data <- left_join(phenology,raw, by = "filename_image")

```

## check whether flower-leaf sequence changed

```{r eval=FALSE}
joint_data_flower_leaf <- joint_data %>% 
  dplyr::select(has_leaves, is_fertile) %>% 
  # 
```

## check whetehr flowering order across speceis changed
```{r}
npn_data <- read.csv("../data/npn_temperature_data.csv") %>% 
  mutate(dataset = "Field observation") %>% 
  dplyr::select(yeart, norm, anom, doy, species, genus, dataset, year)
herb_data <- read.csv("../data/herb_temperature_data.csv") %>% 
  mutate(dataset = "Herbarium") %>%
  dplyr::select(yeart, norm, anom, doy, species, genus, dataset, year)

joint_data_flower <- rbind(npn_data, herb_data) 
```


```{r}
# Create a vector of species with >80 records before 1950
species_list <- joint_data_flower %>% 
  filter(year < 1950) %>% 
  group_by(species) %>% 
  filter(n() > 80) %>% 
  distinct(species) %>% 
  pull(species)

# Plot flower time order for those species
joint_data_flower %>% 
  filter(year < 1950) %>% 
  filter(species %in% species_list) %>% 
  ggplot() +
  geom_density(aes(x = doy, color = species))


joint_data_flower %>% 
  filter(year < 1950) %>% 
  filter(species %in% species_list) %>% 
  
```

```{r}
joint_data_flower %>% 
  filter(year>1950) %>% 
  filter(species %in% species_list) %>% 
  ggplot() +
  geom_density(aes(x = doy, color = species))
```

